apiVersion: v2
name: argocd
description: Argo CD component for Karavel
type: application
version: 1.2.0-SNAPSHOT
appVersion: 2.5.5
maintainers:
  - name: MatteoJoliveau
    email: matteo.joliveau@mikamai.com

home: https://argo-cd.readthedocs.io
sources:
  - https://github.com/argoproj/argo-cd/
  - https://github.com/karavel-io/platform-component-argocd

annotations:
  karavel.io/bootstrap: 'true'
  karavel.io/dependencies: cert-manager, external-secrets
  prometheus.enable: prometheus
  grafana.enable: grafana
  dex.enable: dex
  tracing.enable: tempo
