publicURL:
git:
  repo:

adminGroup: ""

# creates the infrastructure-repo-secret from the secure backend
credentialsSecret:
  store:
    name: default
    kind: ClusterSecretStore
  key: ""
  type: ssh

# creates the argocd-secret manifest from the secure backend
secret:
  store:
    name: default
    kind: ClusterSecretStore
  key: ""

dex:
  enable: false
  issuer:
  name: dex
  namespace: dex

oidc:
  config:
    name: SSO
    issuer: https://samples.auth0.com
    clientID: argocd
    clientSecret: $oidc.clientSecret
    cliClientID:
    requestedScopes:
      - openid
      - profile
      - email
      - groups

applicationController:
  replicas: 1

notifications:
  enable: false
  version: 1.1.1
  # creates the argocd-notifications-secret manifest from the secure backend
  secret:
    store:
      name: default
      kind: ClusterSecretStore
    key: ""
  bot:
    enable: false
    publicURL:

redis:
  version: 6.0.9

prometheus:
  enable: true

grafana:
  enable: true

applicationSetController:
  version: v0.2.0
