apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-applicationset-controller
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: applicationset
  name: {{ include "argocd.name" . }}-applicationset-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-applicationset-controller
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: applicationset
  name: {{ include "argocd.name" . }}-applicationset-controller
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
      - applicationsets
      - applicationsets/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applicationsets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - coordination.k8s.io
    resources:
      - configmaps
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-applicationset-controller
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: applicationset
  name: {{ include "argocd.name" . }}-applicationset-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argocd.name" . }}-applicationset-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "argocd.name" . }}-applicationset-controller
