{{- if .Values.notifications.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "argocd.name" . }}-notifications
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-notifications
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - {{ include "argocd.name" . }}-notifications-cm
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - {{ include "argocd.name" . }}-notifications-secret
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argocd.name" . }}-notifications
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-notifications
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argocd.name" . }}-notifications
subjects:
  - kind: ServiceAccount
    name: {{ include "argocd.name" . }}-notifications
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argocd.name" . }}-notifications
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-notifications
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
