{{- if .Values.notifications.enable }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "argocd.name" . }}-notifications-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  secretStoreRef:
    name: {{ .Values.notifications.secret.store.name }}
    kind: {{ .Values.notifications.secret.store.kind }}
  target:
    creationPolicy: 'Owner'
  dataFrom:
    - key: {{ required "param notifications.secret.key is required for generating argocd-secret" .Values.notifications.secret.key }}

{{- end }}
