{{- $url := urlParse (required "parameter publicURL is required for generating certificate" .Values.publicURL) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "argocd.name" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-server
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  rules:
    - host: {{ $url.host }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ include "argocd.name" . }}-server
                port:
                  name: server
  tls:
    - hosts:
        - {{ $url.host }}
      secretName: {{ include "argocd.name" . }}-tls
