{{- if .Values.prometheus.enable }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "argocd.name" . }}-repo-server-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-repo-server-hpa
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: repo-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "argocd.name" . }}-repo-server
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
{{- end }}
