apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argocd.name" . }}-repo-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-repo-server
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: repo-server
