{{- if and .Values.notifications.enable .Values.notifications.bots.slack.enable }}
{{- $url := urlParse (required "parameter notifications.bots.slack.publicURL is required for generating ingress" .Values.notifications.bots.slack.publicURL) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "argocd.name" . }}-notifications-bot
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}-notifications
    {{- include "argocd.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ $url.host }}
      http:
        paths:
          - path: /slack
            pathType: Prefix
            backend:
              service:
                name: {{ include "argocd.name" . }}-notifications-bot
                port:
                  name: http
  tls:
    - hosts:
        - {{ $url.host }}
      secretName: {{ include "argocd.name" . }}-notifications-bot-tls
{{- end }}
