apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd.name" . }}-cm # Argo expects this exact name, so we won't template it
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "argocd.labels" . | nindent 4 }}
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  url: {{ required "parameter publicURL is required for generating certificate" .Values.publicURL }}
  admin.enabled: "false"
  {{- if .Values.dex.enable }}
    {{- with .Values.dex }}
  oidc.config: |
    name: Karavel
    issuer: {{ required "parameter dex.issuer is required for generating the Dex configuration" .issuer }}
    clientID: $dex-{{ include "argocd.name" $ }}-credentials:clientSecret
    clientSecret: $dex-{{ include "argocd.name" $ }}-credentials:clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    requestedIDTokenClaims:
      email:
        essential: true
      groups:
        essential: true
    {{- end }}
    {{- else }}
    {{- with .Values.oidc.config }}
  oidc.config: |
    name: {{ .name }}
    issuer: {{ .issuer }}
    clientID: {{ .clientID }}
    clientSecret: {{ .clientSecret }}
    requestedScopes: {{ .requestedScopes }}
    requestedIDTokenClaims:
      email:
        essential: true
      groups:
        essential: true
    {{- with .cliClientID }}
    cliClientID: {{ . }}
    {{- end }}
    {{- end }}
  {{- end }}
  # Until Velero v1.6.0 is released we've to ignore the Backup resource,
  # because there is no owner reference between the schedule and the backup.
  # When the prune is active, or flagged during a sync, ArgoCD will delete the backup without this exclusion
  resource.exclusions: |
    - apiGroups:
      - "velero.io"
      kinds:
      - Backup
      clusters:
      - "*"
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  timeout.reconciliation: 180s
