apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "argocd.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "argocd.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.credentialsSecret.store.name }}
    kind: {{ .Values.credentialsSecret.store.kind }}
  target:
    creationPolicy: 'Owner'
    template:
      data:
        server.secretkey: ""
        admin.password: ""
        admin.passwordMtime: ""
  dataFrom:
    - key: {{ required "param secret.key is required for generating argocd-secret" .Values.secret.key }}
