{{- if .Values.dex.enable }}
apiVersion: dex.karavel.io/v1alpha1
kind: DexClient
metadata:
  name: {{ include "argocd.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.dex }}
  instanceRef:
    name: {{ .name }}
    namespace: {{ .namespace }}
  {{- end }}
  name: ArgoCD
  redirectUris:
    - {{ required "parameter publicURL is required for generating certificate" .Values.publicURL }}/auth/callback
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
{{- end }}
