apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "argocd.name" . }}-infrastructure-repo-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    name: {{ .Values.credentialsSecret.store.name }}
    kind: {{ .Values.credentialsSecret.store.kind }}
  target:
    creationPolicy: 'Owner'
    template:
      data:
        url: {{ .Values.git.repo }}
  dataFrom:
    - key: {{ required "parameter 'credentialsSecret.key' is required for generating infrastructure-repo-secret" .Values.credentialsSecret.key }}
