apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "argocd.name" . }}-infrastructure-repo-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.credentialsSecret.store.name }}
    kind: {{ .Values.credentialsSecret.store.kind }}
  target:
    creationPolicy: 'Owner'
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: {{ .Values.git.repo }}
        {{- if eq .Values.credentialsSecret.type "ssh" }}
        sshPrivateKey: {{`{{ .sshPrivateKey | base64decode | toString }}` | quote }}
        {{- else }}
        username: {{`{{ .username }}` | quote }}
        password: {{`{{ .password }}` | quote }}
        {{- end }}
  dataFrom:
    - key: {{ required "parameter 'credentialsSecret.key' is required for generating infrastructure-repo-secret" .Values.credentialsSecret.key }}
